### ISSUE TITLE
KML export of all layers 

### ISSUE THREAD

**Issue by grassick** [mWater/mwater-visualization#194]
Any map should be exportable as KML, meaning that all of the layers must be convertible to KML as well. 

Determine what the minimum API surface is to be able to generate KML from an arbitrary layer. Implement that in the Layer interface and then for each layer type. The server should then use that to generate the KML file.

There is limited support for legends in KML. Figure out how to render the react component as a KML supported legend.

Figure out how to render the pop-ups as well in a KML format.
- [ ] Also see if a simplification factor is needed to keep size down
- [x] Add legend to KML

By layer:
## Marker Layer
- [x] Include all sublayers
- [x] Display custom marker shapes and include in kmz
- [x] Display color of points
- [x] Display legend (needs #133)
- [ ] Add custom popup (needs #192)
## Buffer Layer
- [x] Figure out how to order the different colors (#181)
- [x] Draw polygons in correct order so that red is always in front of green, for example
- [ ] Make entire layer have an opacity
- [ ] Add custom popup (needs #192)
## Choropleth Layer
- [x] Draw colored polygons (perhaps with some simplification if KML is way to big)
- [ ] Draw labels of polygons if turned on
- [x] Display legend (needs #133)
- [ ] Add custom popup (needs #192)
